version: '1.0'
name: pipeline-20220826
displayName: pipeline-20220826
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-172e51c3
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gradle
        name: build_gradle
        displayName: Gradle 构建
        jdkVersion: '11'
        gradleVersion: '4.2'
        commands:
          - '# Gradle默认构建命令'
          - chmod +x ./gradlew
          - ./gradlew build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        caches:
          - ~/.gradle/caches
        notify: []
        strategy:
          retry: '0'
